Proyecto_DesarrolloWeb.Web/Models/Pet.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_DesarrolloWeb.Web.Models
{
    public partial class Pet
    {
        public Pet()
        {
            PetImage = new HashSet<PetImage>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? IdPetType { get; set; }
        public int? IdPetBreed { get; set; }
        public string Sex { get; set; }
        public int? IdPetSize { get; set; }
        public int? IdPetAge { get; set; }
        public string Temperament { get; set; }
        public string Video { get; set; }
        public int? IdUser { get; set; }

        public virtual PetAge IdPetAgeNavigation { get; set; }
        public virtual PetBreed IdPetBreedNavigation { get; set; }
        public virtual PetSize IdPetSizeNavigation { get; set; }
        public virtual PetType IdPetTypeNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual ICollection<PetImage> PetImage { get; set; }
    }
}

Proyecto_DesarrolloWeb.Web/Models/PetType.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_DesarrolloWeb.Web.Models
{
    public partial class PetType
    {
        public PetType()
        {
            Pet = new HashSet<Pet>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Pet> Pet { get; set; }
    }

}

Proyecto_DesarrolloWeb.Web/Controllers/PetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto_DesarrolloWeb.Web.Models;
using Proyecto_DesarrolloWeb.Web.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Proyecto_DesarrolloWeb.Web.Controllers
{
    public class PetController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CreatePet()
        {
            ViewBag.petsType = await PetRepo.GetPetsTypeAsync();
            ViewBag.petsAge = await PetRepo.GetPetsAgeAsync();
            ViewBag.petsBreed = await PetRepo.GetPetsBreedAsync();
            ViewBag.petsSize = await PetRepo.GetPetsSizeAsync();

            return View();
        }

        public async Task<IActionResult> RegisterLostPet()
        {
            string idUser = HttpContext.Session.GetString("idUser");

            int userId = Convert.ToInt32(idUser);
            ViewBag.userPets = await PetRepo.GetUserPetsAsync(userId);
            return View();
        }

        public async Task<IActionResult> RegisterPetForAdoption()
        {
            string idUser = HttpContext.Session.GetString("idUser");

            int userId = Convert.ToInt32(idUser);
            ViewBag.userPetsAdoption = await PetRepo.GetUserPetsAsync(userId);
            return View();
        }

        public async Task<IActionResult> RegisterPetFound()
        {
            string idUser = HttpContext.Session.GetString("idUser");

            int userId = Convert.ToInt32(idUser);
            ViewBag.userLostPets = await PetRepo.GetUserLostPetsAsync(userId);
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Registrar(string nombre)
        //{
        //    bool exito = true;

        //    return Json(exito);
        //}

        [HttpPost]
        public async Task<IActionResult> Register (int idUser, string name, int idType, string sex, int idSize, int idAge, 
            int idBreed, string temperament, string url, List<IFormFile> files)
        {
            //INICIO - Codigo para obtener el ID del usuario
            //HttpContext.Session.SetString("idUser", "1");
        
            //FIN - Codigo para obtener el ID del usuario

            List<PetImage> petImages = new List<PetImage>();
            foreach (IFormFile file in files)
            {
                if (file.Length > 0)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        byte[] fileBytes = ms.ToArray();
                        petImages.Add(new PetImage() { Photo = fileBytes });
                        string s = Convert.ToBase64String(fileBytes);
                        // act on the Base64 data
                    }
                }
            }


            var pet = new Pet()
            {
                Name = name,
                IdPetType = idType,
                Sex = sex,
                IdPetSize = idSize,
                IdPetAge = idAge,
                IdPetBreed = idBreed,
                Temperament = temperament,
                Video = url,
                PetImage = petImages,
                IdUser = idUser
            };

            bool exito = await PetRepo.RegisterPetAsync(pet);
            return Json(exito);
        }

        [HttpPost]
        public async Task<IActionResult> InsertLostPet(int idUser, int IdPet, DateTime DateLost, string Description)
        {
            //INICIO - Codigo para obtener el ID del usuario
            //HttpContext.Session.SetString("idUser", "1");
            //int idUser = 1;
            //FIN - Codigo para obtener el ID del usuario

            var lostPet = new LostPet()
            {
                IdUser = idUser,
                IdPet = IdPet,
                DateOfLoss = DateLost,
                DescriptionOfLoss = Description
            };

            var exito = await PetRepo.RegisterLostPetAsync(lostPet);
            return Json(exito);
        }
        //RegisterFoundPetAsync
        [HttpPost]
        public async Task<IActionResult> InsertFoundPet(int idUser, int IdPet, string Description, DateTime DateFound)
        {
            //INICIO - Codigo para obtener el ID del usuario
            //HttpContext.Session.SetString("idUser", "1");
            //int idUser = 1;
            //FIN - Codigo para obtener el ID del usuario

            var foundPet = new LostPet()
            {
                IdUser = idUser,
                IdPet = IdPet,
                DateOfFound = DateFound,
                DescriptionOfFound = Description
            };

            var exito = await PetRepo.RegisterFoundPetAsync(foundPet);
            return Json(exito);
        }


        [HttpPost]
        public async Task<IActionResult> InsertPetAdoption(int idUser, int IdPet, string Description)
        {
            //INICIO - Codigo para obtener el ID del usuario
            //HttpContext.Session.SetString("idUser", "1");
            //int idUser = 1;
            //FIN - Codigo para obtener el ID del usuario

            var petAdoption = new PetAdoption()
            {
                IdUser = idUser,
                IdPet = IdPet,
                Description = Description
            };

            var exito = await PetRepo.RegisterPetAdoptionAsync(petAdoption);
            return Json(exito);
        }
    }
}

Proyecto_DesarrolloWeb.Web/Views/Pet/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Proyecto_DesarrolloWeb.Web/Views/Pet/RegisterLostPet.cshtml
<section class="container py-5">
    <h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">Registrar Mascota Perdida</h1>
    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Este es un espacio para que registres a tu mascota perdida </h2>
    <p class="col-12 col-xl-8 text-left text-muted pb-5 light-300">
        Recuerda que mientras más datos brindes, será mejor para que la gente pueda
        darse una idea de como es la mascota.
    </p>

    <div class="row pb-4">
        <!-- Start Contact Form -->
        <div class="col-lg-8 ">
            <div class="contact-form row">
                @*<form class="contact-form row" method="post" action="#" role="form">*@

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Mascota* </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Elige una de tus mascotas.
                    </p>
                    <select class="custom-select form-select form-select-lg light-300" style="height: calc(3.5rem + 2px);" id="selPet">
                        <option class="light-300" selected>Seleccionar Mascota...</option>
                        @foreach (var item in ViewBag.userPets)
                        {
                            <option class="light-300" value="@item.Id">@item.Name</option>
                        }

                    </select>
                </div><!-- End Input Especie -->

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Fecha de la pérdida* </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Selecciona la fecha en la que se perdio tu mascota.
                    </p>
                    <div class="col-lg-12 mb-4">
                        <input id="myID" type="text" class="form-control form-control-lg light-300" style="height: calc(3.5rem + 2px) !important;" value="Fecha de la pérdida..." />
                    </div><!-- End Input -->
                </div>

                <div class="row pb-xl-5">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Descripción </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Cuentanos donde se perdio, que caracteristicas tiene tu mascota, que ropa u objeto tenia al momento que se perdio. Mientras mas detalles brindes mejor.
                    </p>
                    <div class="col-lg-12 mb-xl-n5">
                        <textarea id="texDescription" class="form-control form-control-lg light-300" rows="8"></textarea>
                    </div><!-- End Input -->
                </div>


                <div class="col-md-12 col-12 m-auto text-end">
                    <button id="btnRegister" type="submit" onclick="funcRegistrar()" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Registrar</button>
                </div>


            </div>
            @*</form>*@
        </div>
        <!-- End Contact Form -->
    </div>

    @*<input id="myID" type="text" />*@

</section>
<!-- End Contact -->

<script>
    var PetRescueDBUser = JSON.parse(localStorage.getItem('PetRescueDBUser'));
    flatpickr("#myID", {});

    function funcRegistrar() {

        let vIdPet = $("#selPet").val();
        let vDateLost = $("#myID").val();
        let vDescription = $("#texDescription").val();

        var formData = new FormData();
        formData.append("IdPet", vIdPet);
        formData.append("DateLost", vDateLost);
        formData.append("Description", vDescription);
        formData.append("idUser", PetRescueDBUser.id);

        //
        //alert(vName);
        //alert(vName);
        //alert(vType);
        //alert(vSex);
        //alert(vSize);
        //alert(vAge);
        //alert(vBreed);
        //alert(vTemperament);
        //alert(vUrl);

        $.ajax({
            type: "Post",
            url: '@Url.Action("InsertLostPet", "Pet")',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            success: function (exito) {
                if (exito) {
                    redirectToHome();
                    @*alert("Se registro correctamente");
                    //cargarListadoClientes();

                    newUrl = '@Url.Action("Index", "Home")';
                    location.href = newUrl;*@

                } else {
                    alert("La mascota ya esta registrada como perdida.");
                }
            }
        });
    }

    function redirectToHome() {
        let timerInterval
        Swal.fire({
          title: 'Registro Exitoso!',
          html: 'Redirigiendo al Inicio <b></b> milliseconds.',
          timer: 2000,
          timerProgressBar: true,
          allowEscapeKey : false,
          allowOutsideClick: false,
          //confirmButtonText: 'Ir al Inicio',
          didOpen: () => {
            Swal.showLoading()
            const b = Swal.getHtmlContainer().querySelector('b')
            timerInterval = setInterval(() => {
              b.textContent = Swal.getTimerLeft()
            }, 100)
          },
          willClose: () => {
            clearInterval(timerInterval)
          }
        }).then((result) => {
          if (result.dismiss === Swal.DismissReason.timer) {
            window.location.href = '@Url.Action("Index","Home")';
          }
        })
    }

</script>

Proyecto_DesarrolloWeb.Web/Views/Pet/RegisterPetForAdoption.cshtml
<section class="container py-5">

    <h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">Registrar Mascota Para Adopción</h1>
    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Este es un espacio para que registres a tu mascota para darla en adopción </h2>
    <p class="col-12 col-xl-8 text-left text-muted pb-5 light-300">
        Recuerda que mientras más datos brindes, será mejor para que la gente pueda
        darse una idea de como es la mascota.
    </p>

    <div class="row pb-4">
        <!-- Start Contact Form -->
        <div class="col-lg-8 ">
            <div class="contact-form row">
                @*<form class="contact-form row" method="post" action="#" role="form">*@

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Mascota* </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Elige una de tus mascotas.
                    </p>
                    <select class="custom-select form-select form-select-lg light-300" style="height: calc(3.5rem + 2px);" id="selPet">
                        <option class="light-300" selected>Seleccionar Mascota...</option>
                        @foreach (var item in ViewBag.userPetsAdoption)
                            {
                                <option class="light-300" value="@item.Id">@item.Name</option>
                            }

                        @*<option class="light-300" value="1">Gato</option>
                            <option class="light-300" value="2">Perro</option>*@
                    </select>
                </div><!-- End Input Especie -->

                <div class="row pb-xl-5">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Descripción </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Cuentanos cómo es, que características tiene tu mascota, la razón por la que pones tu mascota en adopción. Mientras más detalles brindes mejor.
                    </p>
                    <div class="col-lg-12 mb-xl-n5">
                        <textarea id="texDescription" class="form-control form-control-lg light-300" rows="8"></textarea>
                    </div><!-- End Input -->
                </div>


                <div class="col-md-12 col-12 m-auto text-end">
                    <button id="btnRegister" type="submit" onclick="funcRegistrar()" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Registrar</button>
                </div>


            </div>
            @*</form>*@
        </div>
        <!-- End Contact Form -->
    </div>

    @*<input id="myID" type="text" />*@

</section>
<!-- End Contact -->


<script>
    var PetRescueDBUser = JSON.parse(localStorage.getItem('PetRescueDBUser'));
    flatpickr("#myID", {});

    function funcRegistrar() {

        let vIdPet = $("#selPet").val();
        let vDescription = $("#texDescription").val();

        var formData = new FormData();
        formData.append("IdPet", vIdPet);
        formData.append("Description", vDescription);
        formData.append("idUser", PetRescueDBUser.id);

        $.ajax({
            type: "Post",
            url: '@Url.Action("InsertPetAdoption", "Pet")',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            success: function (exito) {
                if (exito) {
                    @*alert("Se registro correctamente");
                    //cargarListadoClientes();

                    newUrl = '@Url.Action("Index", "Home")';
                    location.href = newUrl;*@
                    redirectToHome();

                } else {
                    alert("La mascota ya esta registrada para adopción.");
                }
            }
        });
    }

    function redirectToHome() {
        let timerInterval
        Swal.fire({
          title: 'Registro Exitoso!',
          html: 'Redirigiendo al Inicio <b></b> milliseconds.',
          timer: 2000,
          timerProgressBar: true,
          allowEscapeKey : false,
          allowOutsideClick: false,
          //confirmButtonText: 'Ir al Inicio',
          didOpen: () => {
            Swal.showLoading()
            const b = Swal.getHtmlContainer().querySelector('b')
            timerInterval = setInterval(() => {
              b.textContent = Swal.getTimerLeft()
            }, 100)
          },
          willClose: () => {
            clearInterval(timerInterval)
          }
        }).then((result) => {
          if (result.dismiss === Swal.DismissReason.timer) {
            window.location.href = '@Url.Action("Index","Home")';
          }
        })
    }

</script>

Proyecto_DesarrolloWeb.Web/Views/Pet/RegisterPetFound.cshtml
<section class="container py-5">

    <h1 class="col-12 col-xl-8 h2 text-left text-primary pt-3">¡Mascota Encontrada!</h1>
    <h2 class="col-12 col-xl-8 h4 text-left regular-400">¡Felicidades! Nos da mucho gusto que hayas podido encontrar a tu mascota.  </h2>
    <p class="col-12 col-xl-8 text-left text-muted pb-5 light-300">
        Por favor tomate unos minutos para que nos cuentes tu experiencia y asi ayudar a esta comunidad a que utilicen este medio para encontrar a sus mascotas perdidas.
    </p>

    <div class="row pb-4">
        <!-- Start Contact Form -->
        <div class="col-lg-8 ">
            <div class="contact-form row">
                @*<form class="contact-form row" method="post" action="#" role="form">*@

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Mascota* </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Elige una de tus mascotas. Tener en cuenta que solo apareceran tus mascotas que se encuentren en estado de perdidas.
                    </p>
                    <select class="custom-select form-select form-select-lg light-300" style="height: calc(3.5rem + 2px);" id="selPet">
                        <option class="light-300" selected>Seleccionar Mascota...</option>
                        @foreach (var item in ViewBag.userLostPets)
                {
                    <option class="light-300" datelost="@item.DateOfLoss" value="@item.IdPet">@item.Name</option>
                }

                        @*<option class="light-300" value="1">Gato</option>
                <option class="light-300" value="2">Perro</option>*@
                    </select>
                </div><!-- End Input Especie -->

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Fecha de la pérdida </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Este campo es solo informativo, aqui se mostrara la fecha en que se perdio tu mascota.
                    </p>
                    <div class="col-lg-12 mb-4">
                        <input id="inpDateLost" type="text" disabled="disabled" class="form-control form-control-lg light-300" style="height: calc(3.5rem + 2px) !important;" value="Fecha de la pérdida..." />
                    </div><!-- End Input -->
                </div>

                <div class="col-lg-12 mb-4">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Fecha de encuentro* </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Selecciona la fecha en la que encontraste a tu mascota.
                    </p>
                    <div class="col-lg-12 mb-4">
                        <input id="myID" type="text" class="form-control form-control-lg light-300" style="height: calc(3.5rem + 2px) !important;" value="Fecha de encuentro..." />
                    </div><!-- End Input -->
                </div>

                <div class="row pb-xl-5">
                    <h2 class="col-12 col-xl-8 h4 text-left regular-400">Descripción </h2>
                    <p class="col-12 col-xl-12 text-left text-muted light-300">
                        Cuentanos cómo encontraste a tu mascota y tu experiencia en general.
                    </p>
                    <div class="col-lg-12 mb-xl-n5">
                        <textarea id="texDescription" class="form-control form-control-lg light-300" rows="8"></textarea>
                    </div><!-- End Input -->
                </div>


                <div class="col-md-12 col-12 m-auto text-end">
                    <button id="btnRegister" type="submit" onclick="funcRegistrar()" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Registrar</button>
                </div>


            </div>
            @*</form>*@
        </div>
        <!-- End Contact Form -->
    </div>

    @*<input id="myID" type="text" />*@

</section>
<!-- End Contact -->

<script>
    var PetRescueDBUser = JSON.parse(localStorage.getItem('PetRescueDBUser'));
    flatpickr("#myID", {});

    $('#selPet').on('change', function () {
        //alert($('#selPet').val());
        //alert($('#selPet').html());
        //alert($('#selPet :selected').text());
        //.data(key)
       //alert($('#selPet :selected').attr("datelost"));
        var date = $('#selPet :selected').attr("datelost")
        var dateLost = date.substring(0, 10);
        $("#inpDateLost").val(dateLost);
    });

    function funcRegistrar() {

        let vIdPet = $("#selPet").val();
        let vDescription = $("#texDescription").val();
        let vDateFound = $("#myID").val();
        var formData = new FormData();
        formData.append("IdPet", vIdPet);
        formData.append("Description", vDescription);
        formData.append("DateFound", vDateFound);
        formData.append("idUser", PetRescueDBUser.id);
        //alert("llego hasta aca");
        $.ajax({
            type: "Post",
            url: '@Url.Action("InsertFoundPet", "Pet")',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            success: function (exito) {
                if (exito) {
                    @*alert("Se registro correctamente");
                    //cargarListadoClientes();

                    newUrl = '@Url.Action("Index", "Home")';
                    location.href = newUrl;*@
                    redirectToHome();

                } else {
                    alert("La mascota ya esta registrada para adopción.");
                }
            }
        });
    }

     function redirectToHome() {
        let timerInterval
        Swal.fire({
          title: 'Registro Exitoso!',
          html: 'Redirigiendo al Inicio <b></b> milliseconds.',
          timer: 2000,
          timerProgressBar: true,
          allowEscapeKey : false,
          allowOutsideClick: false,
          //confirmButtonText: 'Ir al Inicio',
          didOpen: () => {
            Swal.showLoading()
            const b = Swal.getHtmlContainer().querySelector('b')
            timerInterval = setInterval(() => {
              b.textContent = Swal.getTimerLeft()
            }, 100)
          },
          willClose: () => {
            clearInterval(timerInterval)
          }
        }).then((result) => {
          if (result.dismiss === Swal.DismissReason.timer) {
            window.location.href = '@Url.Action("Index","Home")';
          }
        })
    }
</script>